using System;
using System.Collections.Generic;
using System.Linq;
using SimonSends;
using UnityEngine;
using Rnd = UnityEngine.Random;

/// <summary>
/// On the Subject of Simon Sends
/// Created by Timwi
/// </summary>
public class SimonSendsModule : MonoBehaviour
{
    public KMBombInfo Bomb;
    public KMBombModule Module;
    public KMAudio Audio;

    public static string[][] _text = @"THIS IS THE FIRST WORD FOR THE PURPOSES OF COUNTING WORDS AND PARAGRAPHS IN THIS MANUAL
HYPHENATED WORDS COUNT AS A SINGLE WORD PUNCTUATION MARKS DO NOT COUNT AS LETTERS
THE MODULE CONTAINS THREE COLORED LEDS RED GREEN AND BLUE WHICH FLASH THREE LETTERS IN MORSE CODE AT THE SAME TIME
HOWEVER DUE TO THEIR CLOSE PROXIMITY THE LIGHT FROM MULTIPLE LIT LEDS COMBINES ACCORDING TO ADDITIVE COLOR MIXING
CONVERT EACH OF THE LETTERS INTO A NUMBER BY USING THE LETTERS ALPHABETIC POSITION AND CALL THESE NUMBERS R G AND B
CONSTRUCT A NEW MULTICOLORED MORSE CODE MESSAGE BY COMBINING A RED GREEN AND BLUE LETTER DETERMINED AS FOLLOWS
THE RTH LETTER FROM THE START OF THE GTH WORD FROM THE START OF THE BTH PARAGRAPH IN THIS MANUAL IS THE NEW RED LETTER
THE GTH LETTER FROM THE START OF THE BTH WORD FROM THE START OF THE RTH PARAGRAPH IN THIS MANUAL IS THE NEW GREEN LETTER
THE BTH LETTER FROM THE START OF THE RTH WORD FROM THE START OF THE GTH PARAGRAPH IN THIS MANUAL IS THE NEW BLUE LETTER
A DOT IN MORSE CODE IS ONE UNIT LONG A DASH IS THREE THE GAP BETWEEN DASHES AND DOTS IS ONE UNIT
USING THE SAME ADDITIVE COLOR MIXING ENTER THE RESULT USING THE EIGHT COLORED BUTTONS ON THE MODULE
A MISTAKE RESULTS IN AN IMMEDIATE STRIKE CONTINUE ENTERING THE CODE WHERE YOU LEFT OFF
WRAP AROUND TO THE FIRST WORD IF WHILE COUNTING LETTERS YOU REACH THE LAST WORD WHICH IS THIS".Replace("\r", "").Split('\n').Select(line => line.Split(' ')).ToArray()

    private static int _moduleIdCounter = 1;
    private int _moduleId;

    void Start()
    {
        _moduleId = _moduleIdCounter++;
    }
}
